export {}
declare global {
  const Accordion: typeof import('components/shared/Accordion.astro')['default']
  const App: typeof import('layouts/App.astro')['default']
  const Button: typeof import('components/shared/Button.astro')['default']
  const Card: typeof import('components/shared/Card.astro')['default']
  const Col: typeof import('components/shared/Col.astro')['default']
  const H1: typeof import('components/shared/H1.astro')['default']
  const H2: typeof import('components/shared/H2.astro')['default']
  const H3: typeof import('components/shared/H3.astro')['default']
  const H4: typeof import('components/shared/H4.astro')['default']
  const H5: typeof import('components/shared/H5.astro')['default']
  const Img: typeof import('components/shared/Img.astro')['default']
  const P: typeof import('components/shared/P.astro')['default']
  const Row: typeof import('components/shared/Row.astro')['default']
  const TheCatalog: typeof import('components/TheCatalog.astro')['default']
  const TheFooter: typeof import('components/TheFooter.astro')['default']
  const TheForm: typeof import('components/TheForm.astro')['default']
  const TheHeader: typeof import('components/TheHeader.astro')['default']
  const ThePopup: typeof import('components/ThePopup.astro')['default']
  const TheSection: typeof import('components/TheSection.astro')['default']
}