const products = [
  {
    img: "products/1.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 3888000,
    status: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/2.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 7888000,
    status: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/3.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 1888000,
    status: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/1.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 3888000,
    status: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/2.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 1888000,
    status: "Б/У",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/3.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 3888000,
    status: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/1.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 9888000,
    status: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/2.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 3888000,
    status: "Б/У",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/3.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 4888000,
    status: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/1.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 3888000,
    status: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/2.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 5888000,
    status: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/3.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 6888000,
    status: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/1.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 3888000,
    status: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/2.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 7888000,
    status: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/3.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 1888000,
    status: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/1.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 3888000,
    status: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/2.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 1888000,
    status: "Б/У",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/3.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 3888000,
    status: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/1.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 9888000,
    status: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/2.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 3888000,
    status: "Б/У",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/3.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 4888000,
    status: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/1.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 3888000,
    status: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/2.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 5888000,
    status: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
  },
  {
    img: "products/3.png",
    title: "Швейцарские часы Rolex Rolex Day-Date 40 mm White Gold 228239-0007",
    price: 6888000,
    status: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
  },
];

export { products };
